/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karen
 */
public class PRESENTACION extends javax.swing.JPanel {

    /**
     * Creates new form PRESENTACION
     */
    public PRESENTACION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        APP = new javax.swing.JLabel();
        PRESENTACION = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JB_SIGUIENTE = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        APP.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        APP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        APP.setText("SEEAPP");

        jLabel1.setText("ES UN APLICATIVO QUE VA AYUDAR A LAS PERSONAS CIEGAS A LLEGAR A SITIOS EN ESPECIFICOS.");

        javax.swing.GroupLayout PRESENTACIONLayout = new javax.swing.GroupLayout(PRESENTACION);
        PRESENTACION.setLayout(PRESENTACIONLayout);
        PRESENTACIONLayout.setHorizontalGroup(
            PRESENTACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRESENTACIONLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PRESENTACIONLayout.setVerticalGroup(
            PRESENTACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRESENTACIONLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        JB_SIGUIENTE.setText("SIGUIENTE");
        JB_SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SIGUIENTEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PRESENTACION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JB_SIGUIENTE)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(APP, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(APP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PRESENTACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(JB_SIGUIENTE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JB_SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SIGUIENTEActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_JB_SIGUIENTEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APP;
    private javax.swing.JButton JB_SIGUIENTE;
    private javax.swing.JPanel PRESENTACION;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
